### PR TITLE
Updated broken link to Anaconda

### PR DESCRIPTION
**Pull request by RaInta**

### CODE REVIEW

**Comment by hmert** [comment]
@RaInta could you rebase your PR?

**Comment by RaInta** [comment]
Ahh, sorry for the mess! 

I have typos in some of these commits as well. I'll cancel this one and put in another PR.
Thanks!

**Comment by RaInta** [comment]
Please let me know if this was the right thing to do here --- I had trouble rebasing this.

**Comment by hmert** [comment]
Yep, please open new PR.

**Pull request closed without merging**
